# Generated by Django 3.2 on 2021-04-28 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('opt_description', models.TextField(verbose_name='optional description')),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('opt_description', models.TextField(verbose_name='optional description')),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_name', models.CharField(max_length=256, verbose_name='optional name')),
                ('opt_description', models.TextField(verbose_name='optional description')),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('section_category', models.CharField(choices=[('PROC', 'Procedure'), ('PROP', 'Property'), ('LEM', 'Lemma'), ('ASS', 'Assertion'), ('INV', 'Invariant'), ('PRE', 'Precondition'), ('POST', 'Postcondition')], max_length=4)),
                ('status', models.CharField(choices=[('PR', 'Proved'), ('IN', 'Invalid'), ('CO', 'Counterexample'), ('UN', 'Unchecked')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('login', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('file_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_file_section', to='prover.filesection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prover.user')),
            ],
        ),
    ]
