# Generated by Django 3.2 on 2021-04-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0003_file_file_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_field',
            new_name='file_data',
        ),
    ]
