# Generated by Django 3.2 on 2021-04-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0004_rename_file_field_file_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
