# Generated by Django 3.2 on 2021-04-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0005_auto_20210429_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='parent_dir',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prover.directory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='file',
            name='opt_description',
            field=models.CharField(blank=True, max_length=256, verbose_name='optional description'),
        ),
        migrations.AlterField(
            model_name='filesection',
            name='opt_description',
            field=models.CharField(blank=True, max_length=256, verbose_name='optional description'),
        ),
    ]
