# Generated by Django 3.2 on 2021-04-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0007_auto_20210429_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
