# Generated by Django 3.2 on 2021-04-29 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0008_alter_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
