# Generated by Django 3.2 on 2021-04-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0009_remove_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='opt_parent_dir',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='prover.directory'),
            preserve_default=False,
        ),
    ]
