# Generated by Django 3.2 on 2021-04-30 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0010_directory_opt_parent_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='opt_parent_dir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prover.directory'),
        ),
    ]
