# Generated by Django 3.2 on 2021-05-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prover', '0012_auto_20210430_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
    ]
